added conditional. patch for use on Debian 12
-- error fixed:
  -- typeerror: create_key() got an unexpected keyword argument 'timeout'

-- added conditionals in lines 703 and 720

-- create_key function updated because ChatGPT said so (this was the actual fix, i think)